### ISSUE TITLE
The Rails 7 Way

### ISSUE THREAD

**Issue by moonglum** [fpsvogel/learn-ruby#3]
Thanks for this great resource! Are you open to add the book [The Rails 7 Way](https://leanpub.com/therails7way)? It is an advanced Rails book :smiley:

**Comment by fpsvogel** [comment]
You know, at various times in the past I've thought "I should read that" but I've just never added it to the list. Now I've added it ([75c5701](https://github.com/fpsvogel/learn-ruby/commit/75c5701203b84286ba11931e4dc5db4f021ebcaf)).

Looking forward to reading it. Thanks for the suggestion!

**Comment by moonglum** [comment]
You're welcome :bow:
