### ISSUE TITLE
Full Stack Rails Mastery course

### ISSUE THREAD

**Issue by hrishimittal** [fpsvogel/learn-ruby#5]
@fpsvogel Thanks for putting together this awesome collection of resources. I'd like to suggest my course [Full Stack Rails Mastery](https://learnetto.com/users/hrishio/courses/full-stack-rails-mastery). It's an intermediate level course. Thanks!

**Comment by fpsvogel** [comment]
Thanks for the suggestion! I actually pre-ordered your course a while ago (in 2020?) but then I didn't notice when content started to be added to it, so I'm glad you mentioned it here. I'll give it a try, and if I feel that it fills a gap then I'll add it to the list.

**Comment by hrishimittal** [comment]
@fpsvogel Thanks!
